name: CI Tests (All Branches)

on:
  push:
  pull_request:

env:
  NXF_ANSI_LOG: false
  NXF_VER: '24.04.4'

jobs:
  validate:
    name: Validate Pipeline
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ env.NXF_VER }}"

      - name: Validate pipeline syntax
        run: |
          nextflow config ${GITHUB_WORKSPACE} -profile test,github_actions

      - name: Test pipeline help
        run: |
          nextflow run ${GITHUB_WORKSPACE} --help

  test:
    name: Run pipeline test
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name == 'push' && (contains(github.ref, 'main') || contains(github.ref, 'dev'))
    
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ env.NXF_VER }}"

      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} \
            -profile test,github_actions \
            -c conf/independent.config \
            --outdir ./results
            
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ github.ref_name }}-${{ github.run_number }}
          path: |
            ./results/
            .nextflow.log
