name: CI Tests

on:
  push:
    branches: [ main, develop, master, dev ]
  pull_request:
    branches: [ main, master, develop, dev ]

env:
  NXF_ANSI_LOG: false
  NXF_VER: '24.04.4'

jobs:
  test:
    name: Run pipeline tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ env.NXF_VER }}"

      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} \
            -profile test,github_actions \
            -c conf/independent.config \
            --outdir ./results
            
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ github.run_number }}
          path: |
            ./results/
            .nextflow.log
